server:
  port: 8091

spring:
  application:
    name: user-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.101:8848
        namespace: 12dfa2ce-903d-4a80-8ecb-5abf543562e3
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fil_user?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
  sleuth:
    sampler:
      probability: 1.0
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: 300
        max-idle: 100
        min-idle: 0
        max-wait: -1ms

# 开启 feign 的熔断功能,设置feign客户端超时时间
feign:
  httpclient:
    enabled: true
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 10000
        connectTimeout: 10000

mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mei.hui.user.entity

#showSql
logging:
  level:
    com.mei.hui.user.mapper: debug

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# swagger 开关
swagger:
  is:
    enable: true


# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.3.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/home/minerUpload
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

sms:
  url: http://www.lokapi.cn/smsUTF8.aspx
  username: 18618197958
  password: 18618197958
  token: bcde6d7d
  templateId: 8C288D13
