server:
  port: 8071

spring:
  application:
    name: gateway
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 4d0b7fdb-5c4b-4abb-adfb-b677249c49b4
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: user-server
        uri: lb://user-server
        predicates:
        - Path=/user-server/**
        filters:
        - StripPrefix=1
      - id: miner-server
        uri: lb://miner-server
        predicates:
        - Path=/miner-server/**
        filters:
        - StripPrefix=1

# 开启 feign 的熔断功能,设置feign客户端超时时间
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 10000 # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
        connectTimeout: 10000 # 指的是建立连接后从服务器读取到可用资源所用的时间。