server:
  port: 8081

spring:
  application:
    name: miner-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 4d0b7fdb-5c4b-4abb-adfb-b677249c49b4
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/miner_pool?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
  sleuth:
    sampler:
      probability: 1.0

# 开启 feign 的熔断功能,设置feign客户端超时时间
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 10000
        connectTimeout: 10000

mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mei.hui.miner.entity

#showSql
logging:
  level:
    com.mei.hui.miner.mapper: debug
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# swagger 开关
swagger:
  is:
    enable: true
