server:
  port: 8082

spring:
  application:
    name: miner-server
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.15.3:8848
        namespace: 013be443-9f4c-4106-9c96-b34b7211a38b
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fil_miner?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  sleuth:
    sampler:
      probability: 1.0

# 开启 feign 的熔断功能,设置feign客户端超时时间
feign:
  httpclient:
    enabled: true
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 10000
        connectTimeout: 10000

mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mei.hui.miner.entity

#showSql
logging:
  level:
    com.mei.hui.miner.mapper: debug
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# swagger 开关
swagger:
  is:
    enable: true
